Shop.create(name: "Music World", location: "123 Main Street")
Shop.create(name: "Melody Mart", location: "456 Oak Avenue")
Shop.create(name: "Harmony Music Shop", location: "789 Elm Road")

Instrument.create(name: "Acoustic Guitar", brand: "Fender", family: "String", price: 500, shop_id: 1)
Instrument.create(name: "Electric Guitar", brand: "Gibson", family: "String", price: 1000, shop_id: 2)
Instrument.create(name: "Piano", brand: "Yamaha", family: "Keyboard", price: 2000, shop_id: 3)
Instrument.create(name: "Drums", brand: "Pearl", family: "Percussion", price: 800, shop_id: 1)
Instrument.create(name: "Violin", brand: "Stradivarius", family: "String", price: 5000, shop_id: 2)
Instrument.create(name: "Trumpet", brand: "Bach", family: "Brass", price: 1200, shop_id: 3)
Instrument.create(name: "Flute", brand: "Yamaha", family: "Woodwind", price: 800, shop_id: 1)
Instrument.create(name: "Saxophone", brand: "Selmer", family: "Woodwind", price: 2500, shop_id: 2)
Instrument.create(name: "Cello", brand: "D'Addario", family: "String", price: 3000, shop_id: 3)
